# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{grapi}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aurelian Oancea"]
  s.date = %q{2009-12-29}
  s.description = %q{Ruby client for unofficial Google Reader API}
  s.email = %q{oancea@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "grapi.gemspec",
     "lib/core_ext/string.rb",
     "lib/grapi.rb",
     "lib/grapi/reader.rb",
     "test/helper.rb",
     "test/test_grapi.rb"
  ]
  s.homepage = %q{http://github.com/aurelian/grapi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby client for unofficial Google Reader API}
  s.test_files = [
    "test/helper.rb",
     "test/test_grapi.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<curb>, [">= 0.6.1.0"])
    else
      s.add_dependency(%q<curb>, [">= 0.6.1.0"])
    end
  else
    s.add_dependency(%q<curb>, [">= 0.6.1.0"])
  end
end

